import Head from 'next/head'
import { Inter } from '@next/font/google'
import Navbar from '@/components/Navbar/Navbar'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

const styles = {
    backgroundColor: '#FBFBFB',
}

export default function Layout(props: any): any {
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={styles}>
        <Navbar />
        <div>
            {props.children}
        </div>
      </main>
    </>
  )
}
