import Navbar from "@/components/Navbar/Navbar";
import Head from "next/head";
import styles from '@/styles/CreateProject.module.css'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { IoLogoGoogle } from "react-icons/io5";


export default function CreateProject() {
    return (
        <>
            <Head>
                <title>Create Project | getDONE</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Navbar />

                <div className={styles.text}>
                    <h1 className={styles.heading}>Create Project</h1>
                    <form className={styles.form}>

                        <input type="email" name="" id="" placeholder="Enter your project name..." className={styles.inputs} />
                        <input type="text" name="" id="" placeholder="Enter tags related to the project..." className={styles.inputs} />
                        <input type="password" name="" id="" placeholder="Enter your project deadline..." className={styles.inputs} />

                        <input type="submit" value="Continue" id="" placeholder="Enter your password..." className={styles.submitInput} />
                    </form>
                </div>
            </main>
        </>
    )
}