import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Logo from '@/components/Logo'
import Navbar from '@/components/Navbar/Navbar'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowRight, faArrowRightArrowLeft, faRightFromBracket } from '@fortawesome/free-solid-svg-icons'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <div className={styles.text}>
          <h1 className={styles.heading}>Are you working on a project? </h1>
          <p className={styles.paragraph}><span className={styles.bold}>getDone</span> is the choice to <span className={styles.boldUnderline}>focus</span> and <span className={styles.boldUnderline}>manage</span> your projects effectively!</p>
          <button className={styles.buttonRegister}>Get Started

            <FontAwesomeIcon
              icon={faArrowRight}
              className={styles.icon}
            />
          </button>
        </div>
      </main>
    </>
  )
}
