import Navbar from "@/components/Navbar/Navbar";
import Head from "next/head";
import styles from '@/styles/Login.module.css'
import { useRef, useState } from "react";
import { toast, Toast, Toaster } from "react-hot-toast";
import { useRouter } from "next/router";

export default function Login() {

    const [email, setEmail] = useState<string>("");
    const [password, setPassword] = useState<string>("");
    const router = useRouter()

    // handle submit
    const handleSubmit = (e: React.FormEvent<HTMLInputElement>): void => {
        e.preventDefault()
        if (!email || !password) {
            toast.error("Missing field!")
            return;
        }
        let reg = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w\w+)+$/;
        if (reg.test(email) === false) {
            toast.error("Enter valid email!") 
        }
        router.push("/dashboard")
    }

    return (
        <>
            <Head>
                <title>Login | getDONE</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div><Toaster /></div>
                <Navbar />

                <div className={styles.text}>
                    <h1 className={styles.heading}>Log in</h1>
                    {/* @ts-ignore */}
                    <form className={styles.form} onSubmit={handleSubmit}>

                        <input onChange={(e) => setEmail(e.target.value)} type="email" name="" id="" placeholder="Enter your email..." className={styles.inputs} />
                        <input onChange={(e) => setPassword(e.target.value)} type="password" name="" id="" placeholder="Enter your password..." className={styles.inputs} />

                        <input type="submit" value="Continue with password" id="" placeholder="Enter your password..." className={styles.submitInput} />
                        <div className={styles.hr}></div>
                        <input type="submit" value="Continue with Google" id="" className={styles.submitInput} />
                    </form>
                </div>
            </main>
        </>
    )
}